# Generated by Django 4.2.1 on 2023-05-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_post_created_response_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Tanks', 'Танки'), ('Healers', 'Хилы'), ('DD', 'ДД'), ('Guildmasters', 'Гилдмастеры'), ('Questgivers', 'Квестгиверы'), ('Smiths', 'Кузнецы'), ('Tanners', 'Кожевники'), ('Potionbrewers', 'Зельевары'), ('Spellmasters', 'Мастера заклинаний')], max_length=254),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
