# Generated by Django 4.2.1 on 2023-05-11 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_alter_post_category_delete_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='name',
        ),
    ]
